 /*
 * (c) Copyright Ascensio System SIA 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package onlyoffice.docspace.api.sdk.apis.People

import onlyoffice.docspace.api.sdk.infrastructure.CollectionFormats.*
import retrofit2.http.*
import retrofit2.Response
import okhttp3.RequestBody
import com.squareup.moshi.Json

import onlyoffice.docspace.api.sdk.models.AccountLoginType
import onlyoffice.docspace.api.sdk.models.Area
import onlyoffice.docspace.api.sdk.models.EmployeeActivationStatus
import onlyoffice.docspace.api.sdk.models.EmployeeArrayWrapper
import onlyoffice.docspace.api.sdk.models.EmployeeFullArrayWrapper
import onlyoffice.docspace.api.sdk.models.EmployeeStatus
import onlyoffice.docspace.api.sdk.models.EmployeeType
import onlyoffice.docspace.api.sdk.models.ErrorApiResponse
import onlyoffice.docspace.api.sdk.models.IAccountEntryArrayWrapper
import onlyoffice.docspace.api.sdk.models.Payments
import onlyoffice.docspace.api.sdk.models.QuotaFilter
import onlyoffice.docspace.api.sdk.models.SortOrder

interface SearchApi {
    /**
     * GET api/2.0/accounts/file/{id}/search
     * Search accounts for a file
     * Searches the portal users and groups that can be given access to the file with the ID given in the route, and  reports for each of them whether it already has access to that file.  The caller has to be allowed to manage the access of that file, and the ID has to belong to an existing file,  so the operation answers 403 for a file the caller cannot share and 404 for an ID that matches nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the file
     *  - 403: No permissions to perform this action
     *  - 404: No file has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithFilesShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-files-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/file/{id}/search")
    suspend fun getAccountsEntriesWithFilesShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/accounts/file/{id}/search
     * Search accounts for a file (third-party storage)
     * Searches the portal users and groups that can be given access to the file with the ID given in the route, and  reports for each of them whether it already has access to that file.  The caller has to be allowed to manage the access of that file, and the ID has to belong to an existing file,  so the operation answers 403 for a file the caller cannot share and 404 for an ID that matches nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the file
     *  - 403: No permissions to perform this action
     *  - 404: No file has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithFilesShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-files-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/file/{id}/search")
    suspend fun getAccountsEntriesWithFilesShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/accounts/folder/{id}/search
     * Search accounts for a folder
     * Searches the portal users and groups that can be given access to the folder with the ID given in the route,  and reports for each of them whether it already has access to that folder.  The caller has to be allowed to manage the access of that folder, and the ID has to belong to an existing  folder, so the operation answers 403 for a folder the caller cannot share and 404 for an ID that matches  nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the folder
     *  - 403: No permissions to perform this action
     *  - 404: No folder has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithFoldersShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-folders-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/folder/{id}/search")
    suspend fun getAccountsEntriesWithFoldersShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/accounts/folder/{id}/search
     * Search accounts for a folder (third-party storage)
     * Searches the portal users and groups that can be given access to the folder with the ID given in the route,  and reports for each of them whether it already has access to that folder.  The caller has to be allowed to manage the access of that folder, and the ID has to belong to an existing  folder, so the operation answers 403 for a folder the caller cannot share and 404 for an ID that matches  nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the folder
     *  - 403: No permissions to perform this action
     *  - 404: No folder has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithFoldersShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-folders-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/folder/{id}/search")
    suspend fun getAccountsEntriesWithFoldersShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/accounts/room/{id}/search
     * Search accounts for a room
     * Searches the portal users and groups that can be given access to the room with the ID given in the route, and  reports for each of them whether it already has access to that room.  The caller has to be allowed to manage the access of that room, and the ID has to belong to an existing room,  so the operation answers 403 for a room the caller cannot share and 404 for an ID that matches nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the room
     *  - 403: No permissions to perform this action
     *  - 404: No room has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithRoomsShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-rooms-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/room/{id}/search")
    suspend fun getAccountsEntriesWithRoomsShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/accounts/room/{id}/search
     * Search accounts for a room (third-party storage)
     * Searches the portal users and groups that can be given access to the room with the ID given in the route, and  reports for each of them whether it already has access to that room.  The caller has to be allowed to manage the access of that room, and the ID has to belong to an existing room,  so the operation answers 403 for a room the caller cannot share and 404 for an ID that matches nothing.  The search is read-only and needs `filterValue`: while it is empty the operation returns an empty list and a  total of 0 instead of every account, so it cannot be used to enumerate the portal.  `filterValue` is matched case-insensitively against the first name, the last name and the email; without  `filterSeparator` it is split on spaces and every term has to match, and with a separator it is split on that  separator and any term may match.  Matching groups are streamed first and users after them, both paged together by `count` and `startIndex`,  while the number of matches is reported in the total count of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.
     * Responses:
     *  - 200: The matching users and groups, each with its access state for the room
     *  - 403: No permissions to perform this action
     *  - 404: No room has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getAccountsEntriesWithRoomsShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-accounts-entries-with-rooms-shared/
     *
     *
     * @param id The ID of the room, folder or file whose access the search is run against, taken from the route. It is an  integer for an entry stored in DocSpace and a provider-specific string for an entry in a connected  third-party storage.
     * @param employeeStatus Keeps only the users in the given account state: `Active` for a working account, `Terminated` for a disabled  one and `Pending` for one that has not accepted its invitation yet. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the users whose activation is in the given state: `NotActivated` for an account that has never  been activated, `Activated` for one that completed the activation, `Pending` for one whose invitation is  still open, and `AutoGenerated` for an account created by the portal itself. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when adding new  members. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when  `excludeShared` is also set. (optional)
     * @param invitedByMe Keeps only the users invited by the caller when true, and only the users invited by somebody else when false.  Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the users invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the users of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page, counting groups and users together. It defaults to 100, which is also the largest value  the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts, counted over the groups and users together. It defaults  to 0, and the total number of matches is reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to search for, matched case-insensitively against the first name, the last name and the email. It is  required in practice: while it is empty the search returns nothing at all rather than every account. (optional)
     * @return [IAccountEntryArrayWrapper]
     */
    @GET("api/2.0/accounts/room/{id}/search")
    suspend fun getAccountsEntriesWithRoomsShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<IAccountEntryArrayWrapper>

    /**
     * GET api/2.0/people/@search/{query}
     * Search users
     * Searches the active accounts of the portal by a term taken from the path, and is the same search as  `GET api/2.0/people/search`, which takes the term in the query string instead.  Only a DocSpace administrator may call it; every other account, including a room admin, gets 403.  Only accounts with the `Active` status are searched, so a pending invitation and a disabled account are never  found - use `GET api/2.0/people/filter` to search across states.  The call is read-only and is not paged: every match is streamed, without a total.  `filterBy` set to `group` turns `text` into a group ID and keeps only the members of that group, so `text`  then has to be a valid identifier.  The answer holds full profiles.
     * Responses:
     *  - 200: The full profiles of the matching active accounts
     *  - 403: The caller is not a DocSpace administrator
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getSearch Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-search/
     *
     *
     * @param query The term to look for, taken from the route. Only accounts with the `Active` status are searched.
     * @param filterBy The only recognised value is `group`, which turns `filterValue` into a group ID and keeps only the members of  that group. Any other value, and omitting the field, applies no group filter. (optional)
     * @param filterValue The group ID to keep the members of, used only when `filterBy` is `group`. It has to be a valid identifier -  a group name is not accepted. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/@search/{query}")
    suspend fun getSearch(@Path("query") query: kotlin.String, @Query("filterBy") filterBy: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>


    /**
    * enum for parameter employeeTypes
    */
    enum class EmployeeTypesGetSimpleByFilter(val value: kotlin.Int) {
        @Json(name = "0") All(0),
        @Json(name = "1") RoomAdmin(1),
        @Json(name = "2") Guest(2),
        @Json(name = "3") DocSpaceAdmin(3),
        @Json(name = "4") User(4)
    }

    /**
     * GET api/2.0/people/simple/filter
     * Filter users in brief
     * Returns a page of portal accounts selected by the full set of account filters, with the short profile of each  of them - the identifying fields, the avatar and the display name, without the contacts, the groups or the  quota.  The caller has to be a room admin, a DocSpace admin or a People module admin; a member or a guest gets 403.  The call is read-only, paged by `count` and `startIndex`, ordered by `sortBy` and `sortOrder`, and reports  the number of matches in the total count of the response.  It accepts exactly the same filters as `GET api/2.0/people/filter` and differs only in how much of each  profile comes back, so prefer this one for pickers, mentions and any list that shows names, and switch to the  other only when the full profile is needed.  Filters combine as conditions that all have to hold, and the same interactions apply: `withoutGroup` makes  `groupId` irrelevant, `employeeType` wins over `employeeTypes`, and `area` cancels the type filters that  contradict it.
     * Responses:
     *  - 200: A page of matching accounts, with their short profiles
     *  - 403: The caller is a member or a guest
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getSimpleByFilter Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-simple-by-filter/
     *
     *
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param groupId Keeps only the members of this group, or excludes them when `excludeGroup` is true. It is ignored when  `withoutGroup` is set. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param employeeType Keeps only the accounts of this single type: `DocSpaceAdmin`, `RoomAdmin`, `User` or `Guest`. When it is  sent it wins over `employeeTypes`, and a type that contradicts `area` is dropped. (optional)
     * @param employeeTypes Keeps the accounts of any of the listed types, combined as alternatives. It is ignored when `employeeType`  is also sent. (optional)
     * @param isAdministrator Set it to true to keep only the DocSpace administrators and the module administrators. Setting it to false  is the same as omitting it and does not exclude administrators. (optional)
     * @param payments Keeps only the accounts that take a paid seat when `Paid`, or only the guests and members that do not when  `Free`. Omit it to search both. (optional)
     * @param accountLoginType Keeps only the accounts that sign in this way: `SSO`, `LDAP`, or `Standart` for an ordinary portal  password. Omit it to search all of them. (optional)
     * @param quotaFilter Keeps only the accounts whose storage quota is the portal default when `Default`, or set individually when  `Custom`. `All`, which is the same as omitting the field, searches both. (optional)
     * @param withoutGroup Set it to true to keep only the accounts that belong to no group at all, which makes `groupId` and  `excludeGroup` irrelevant. (optional)
     * @param excludeGroup Inverts `groupId`: with true the members of that group are left out instead of being the only ones kept. It  has no effect without `groupId`. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only. It also cancels the type filters that contradict  it. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param sortBy What to order the accounts by, compared without regard to case: `FirstName`, `LastName`, `DisplayName`,  `Type`, `Email`, `Department`, `UsedSpace`, `CreatedBy` or `RegistrationDate`. (optional)
     * @param sortOrder The direction of the ordering: `Ascending`, which is the default, or `Descending`. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split  the value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to apply  no text filter at all. (optional)
     * @return [EmployeeArrayWrapper]
     */
    @GET("api/2.0/people/simple/filter")
    suspend fun getSimpleByFilter(@Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("groupId") groupId: java.util.UUID? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("employeeType") employeeType: EmployeeType? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<kotlin.Int>? = null, @Query("isAdministrator") isAdministrator: kotlin.Boolean? = null, @Query("payments") payments: Payments? = null, @Query("accountLoginType") accountLoginType: AccountLoginType? = null, @Query("quotaFilter") quotaFilter: QuotaFilter? = null, @Query("withoutGroup") withoutGroup: kotlin.Boolean? = null, @Query("excludeGroup") excludeGroup: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("sortBy") sortBy: kotlin.String? = null, @Query("sortOrder") sortOrder: SortOrder? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeArrayWrapper>

    /**
     * GET api/2.0/people/file/{id}
     * Search users for a file
     * Returns the accounts that are relevant to the file with the ID given in the route, and reports for each of  them whether it already has access to that file.  The caller only needs read access to the file, not the right to manage its access, but a guest may not call  it at all; an ID that matches no file answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/file/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the file
     *  - 403: The caller is a guest or cannot read the file
     *  - 404: No file has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithFilesShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-files-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/file/{id}")
    suspend fun getUsersWithFilesShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/file/{id}
     * Search users for a file (third-party storage)
     * Returns the accounts that are relevant to the file with the ID given in the route, and reports for each of  them whether it already has access to that file.  The caller only needs read access to the file, not the right to manage its access, but a guest may not call  it at all; an ID that matches no file answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/file/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the file
     *  - 403: The caller is a guest or cannot read the file
     *  - 404: No file has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithFilesShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-files-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/file/{id}")
    suspend fun getUsersWithFilesShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/folder/{id}
     * Search users for a folder
     * Returns the accounts that are relevant to the folder with the ID given in the route, and reports for each of  them whether it already has access to that folder.  The caller only needs read access to the folder, not the right to manage its access, but a guest may not call  it at all; an ID that matches no folder answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/folder/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the folder
     *  - 403: The caller is a guest or cannot read the folder
     *  - 404: No folder has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithFoldersShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-folders-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/folder/{id}")
    suspend fun getUsersWithFoldersShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/folder/{id}
     * Search users for a folder (third-party storage)
     * Returns the accounts that are relevant to the folder with the ID given in the route, and reports for each of  them whether it already has access to that folder.  The caller only needs read access to the folder, not the right to manage its access, but a guest may not call  it at all; an ID that matches no folder answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/folder/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the folder
     *  - 403: The caller is a guest or cannot read the folder
     *  - 404: No folder has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithFoldersShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-folders-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/folder/{id}")
    suspend fun getUsersWithFoldersShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/room/{id}
     * Search users for a room
     * Returns the accounts that are relevant to the room with the ID given in the route, and reports for each of  them whether it already has access to that room.  The caller only needs read access to the room, not the right to manage its access, but a guest may not call  it at all; an ID that matches no room answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/room/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the room
     *  - 403: The caller is a guest or cannot read the room
     *  - 404: No room has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithRoomShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-room-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/room/{id}")
    suspend fun getUsersWithRoomShared(@Path("id") id: kotlin.Int, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/room/{id}
     * Search users for a room (third-party storage)
     * Returns the accounts that are relevant to the room with the ID given in the route, and reports for each of  them whether it already has access to that room.  The caller only needs read access to the room, not the right to manage its access, but a guest may not call  it at all; an ID that matches no room answers 404.  The call is read-only, works without a filter - leaving `filterValue` empty returns every matching account  rather than nothing - and is paged by `count` and `startIndex`, with the number of matches in the total count  of the response.  Pass `excludeShared` to keep only the accounts that have no access yet, `includeShared` to keep only those  that already have it, and neither to get both kinds with the `shared` field telling them apart.  A DocSpace administrator additionally sees the guests that are not related to the caller.  To search users and groups together, or to build an access dialog that needs the right to manage sharing, use  `GET api/2.0/accounts/room/{id}/search` instead.
     * Responses:
     *  - 200: The matching accounts, each with its access state for the room
     *  - 403: The caller is a guest or cannot read the room
     *  - 404: No room has the specified ID
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for getUsersWithRoomShared Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-users-with-room-shared/
     *
     *
     * @param id The ID of the room, folder or file the search is run against, taken from the route. It is an integer for an  entry stored in DocSpace and a provider-specific string for an entry in a connected third-party storage.
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param excludeShared Keeps only the accounts that do not have access to the entry yet, which is the set to offer when granting  access. It takes precedence over `includeShared`, and every returned entry has `shared` set to false. (optional)
     * @param includeShared Keeps only the accounts that already have access to the entry, which is the set to offer when changing or  revoking access. Every returned entry has `shared` set to true, and the flag is ignored when `excludeShared`  is also set. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only - and for a caller who is not a DocSpace  administrator, only the guests that caller is related to. (optional)
     * @param employeeTypes Keeps only the accounts of the listed types, combined as alternatives. An empty list, which is the default,  searches every type. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split the  value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to get  every account the caller may offer access to. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/room/{id}")
    suspend fun getUsersWithRoomShared(@Path("id") id: kotlin.String, @Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("excludeShared") excludeShared: kotlin.Boolean? = null, @Query("includeShared") includeShared: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<EmployeeType>? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>


    /**
    * enum for parameter employeeTypes
    */
    enum class EmployeeTypesSearchUsersByExtendedFilter(val value: kotlin.Int) {
        @Json(name = "0") All(0),
        @Json(name = "1") RoomAdmin(1),
        @Json(name = "2") Guest(2),
        @Json(name = "3") DocSpaceAdmin(3),
        @Json(name = "4") User(4)
    }

    /**
     * GET api/2.0/people/filter
     * Filter users in detail
     * Returns a page of portal accounts selected by the full set of account filters, with the complete profile of  each of them.  The caller has to be a room admin, a DocSpace admin or a People module admin; a member or a guest gets 403,  and a DocSpace admin additionally sees the accounts an ordinary admin does not.  The call is read-only, paged by `count` and `startIndex`, ordered by `sortBy` and `sortOrder`, and reports  the number of matches in the total count of the response.  Filters combine as conditions that all have to hold, with three interactions worth knowing: `withoutGroup`  makes `groupId` irrelevant, `employeeType` wins over `employeeTypes` when both are sent, and `area` set to  `Guests` or `People` cancels the type filters that contradict it.  `GET api/2.0/people/simple/filter` accepts exactly the same filters and returns the short profile instead, so  use that one for pickers and lists and this one when the full profile is really needed.  It is available on an unpaid portal.
     * Responses:
     *  - 200: A page of matching accounts, with their full profiles
     *  - 403: The caller is a member or a guest
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for searchUsersByExtendedFilter Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/search-users-by-extended-filter/
     *
     *
     * @param employeeStatus Keeps only the accounts in the given state: `Active` for working accounts, `Terminated` for disabled ones  and `Pending` for open invitations. Omit it to search every state. (optional)
     * @param groupId Keeps only the members of this group, or excludes them when `excludeGroup` is true. It is ignored when  `withoutGroup` is set. (optional)
     * @param activationStatus Keeps only the accounts whose activation is in the given state: `NotActivated`, `Activated`, `Pending` or  `AutoGenerated`. Omit it to search every state. (optional)
     * @param employeeType Keeps only the accounts of this single type: `DocSpaceAdmin`, `RoomAdmin`, `User` or `Guest`. When it is  sent it wins over `employeeTypes`, and a type that contradicts `area` is dropped. (optional)
     * @param employeeTypes Keeps the accounts of any of the listed types, combined as alternatives. It is ignored when `employeeType`  is also sent. (optional)
     * @param isAdministrator Set it to true to keep only the DocSpace administrators and the module administrators. Setting it to false  is the same as omitting it and does not exclude administrators. (optional)
     * @param payments Keeps only the accounts that take a paid seat when `Paid`, or only the guests and members that do not when  `Free`. Omit it to search both. (optional)
     * @param accountLoginType Keeps only the accounts that sign in this way: `SSO`, `LDAP`, or `Standart` for an ordinary portal  password. Omit it to search all of them. (optional)
     * @param quotaFilter Keeps only the accounts whose storage quota is the portal default when `Default`, or set individually when  `Custom`. `All`, which is the same as omitting the field, searches both. (optional)
     * @param withoutGroup Set it to true to keep only the accounts that belong to no group at all, which makes `groupId` and  `excludeGroup` irrelevant. (optional)
     * @param excludeGroup Inverts `groupId`: with true the members of that group are left out instead of being the only ones kept. It  has no effect without `groupId`. (optional)
     * @param invitedByMe Keeps only the accounts invited by the caller when true, and only those invited by somebody else when  false. Omit it to search regardless of who sent the invitation. (optional)
     * @param inviterId Keeps only the accounts invited by the account with this ID. Omit it to search regardless of who sent the  invitation. (optional)
     * @param area The part of the portal to search in: `All`, the default, searches members and guests together, `People`  leaves the guests out, and `Guests` returns guests only. It also cancels the type filters that contradict  it. (optional)
     * @param count The size of the page. It defaults to 100, which is also the largest value the operation accepts. (optional)
     * @param startIndex The number of matches to skip before the page starts. It defaults to 0, and the total number of matches is  reported in the total count of the response. (optional)
     * @param sortBy What to order the accounts by, compared without regard to case: `FirstName`, `LastName`, `DisplayName`,  `Type`, `Email`, `Department`, `UsedSpace`, `CreatedBy` or `RegistrationDate`. (optional)
     * @param sortOrder The direction of the ordering: `Ascending`, which is the default, or `Descending`. (optional)
     * @param filterSeparator The character that splits `filterValue` into several terms, of which any one may match. Omit it to split  the value on spaces instead, in which case every term has to match. (optional)
     * @param filterValue The text to match against the first name, the last name and the email, case-insensitively. Omit it to apply  no text filter at all. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/filter")
    suspend fun searchUsersByExtendedFilter(@Query("employeeStatus") employeeStatus: EmployeeStatus? = null, @Query("groupId") groupId: java.util.UUID? = null, @Query("activationStatus") activationStatus: EmployeeActivationStatus? = null, @Query("employeeType") employeeType: EmployeeType? = null, @Query("employeeTypes") employeeTypes: @JvmSuppressWildcards kotlin.collections.List<kotlin.Int>? = null, @Query("isAdministrator") isAdministrator: kotlin.Boolean? = null, @Query("payments") payments: Payments? = null, @Query("accountLoginType") accountLoginType: AccountLoginType? = null, @Query("quotaFilter") quotaFilter: QuotaFilter? = null, @Query("withoutGroup") withoutGroup: kotlin.Boolean? = null, @Query("excludeGroup") excludeGroup: kotlin.Boolean? = null, @Query("invitedByMe") invitedByMe: kotlin.Boolean? = null, @Query("inviterId") inviterId: java.util.UUID? = null, @Query("area") area: Area? = null, @Query("count") count: kotlin.Int? = null, @Query("startIndex") startIndex: kotlin.Int? = null, @Query("sortBy") sortBy: kotlin.String? = null, @Query("sortOrder") sortOrder: SortOrder? = null, @Query("filterSeparator") filterSeparator: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/search
     * Search users by query
     * Searches the active accounts of the portal by a term passed in the query string, and is the same search as  `GET api/2.0/people/@search/{query}`, which takes the term in the path instead.  Only a DocSpace administrator may call it; every other account, including a room admin, gets 403.  Only accounts with the `Active` status are searched, so a pending invitation and a disabled account are never  found - use `GET api/2.0/people/filter` to search across states.  The call is read-only and is not paged: every match is streamed, without a total.  It takes the search term and nothing else - the group filter of  `GET api/2.0/people/@search/{query}` is not reachable here, because the handler forwards only `query` - so  use that operation when the result has to be narrowed to one group.  The answer holds full profiles, because the handler passes the request on to the operation that builds the  complete profile.
     * Responses:
     *  - 200: The full profiles of the matching active accounts
     *  - 403: The caller is not a DocSpace administrator
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for searchUsersByQuery Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/search-users-by-query/
     *
     *
     * @param query The term to look for. Only accounts with the `Active` status are searched, and this is the only parameter the  operation reads. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/search")
    suspend fun searchUsersByQuery(@Query("query") query: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

    /**
     * GET api/2.0/people/status/{status}/search
     * Search users by status filter
     * Searches the accounts that are in one particular state - the status is taken from the route - and whose name,  user name, email or contacts contain the search term.  Only a DocSpace administrator may call it; every other account, including a room admin, gets 403.  The call is read-only and is not paged: it matches in memory over every account of that status and streams  all of them, so it is meant for administrative lookups rather than for a user-facing list - use  `GET api/2.0/people/filter` when a page and a total are needed.  The term is matched as a case-insensitive substring and is required; `filterBy` set to `group` turns `text`  into a group ID and keeps only the members of that group, so `text` then has to be a valid identifier.  The answer holds full profiles, in no particular order.
     * Responses:
     *  - 200: The full profiles of the matching accounts
     *  - 403: The caller is not a DocSpace administrator
     *  - 401: Unauthorized
     *  - 429: Too Many Requests.
     *  - 500: Internal Server Error.
     *  - 400: Bad Request.
     *  - 502: Bad Gateway. Returned by the reverse proxy, response body may be HTML and not JSON.
     *  - 503: Service Unavailable. Returned by the reverse proxy, response body may be HTML and not JSON.
     *
     * REST API Reference for searchUsersByStatus Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/search-users-by-status/
     *
     *
     * @param status The account state to search in, taken from the route: `Active` for working accounts, `Terminated` for  disabled ones, `Pending` for open invitations, or `All` for every state.
     * @param query The term to look for, matched as a case-insensitive substring of the first name, the last name, the user  name, the email and the contacts. It is required in practice, because the search cannot run without it. (optional)
     * @param filterBy The only recognised value is `group`, which turns `filterValue` into a group ID and keeps only the members of  that group. Any other value, and omitting the field, applies no group filter. (optional)
     * @param filterValue The group ID to keep the members of, used only when `filterBy` is `group`. It has to be a valid identifier -  a group name is not accepted. (optional)
     * @return [EmployeeFullArrayWrapper]
     */
    @GET("api/2.0/people/status/{status}/search")
    suspend fun searchUsersByStatus(@Path("status") status: EmployeeStatus, @Query("query") query: kotlin.String? = null, @Query("filterBy") filterBy: kotlin.String? = null, @Query("filterValue") filterValue: kotlin.String? = null): Response<EmployeeFullArrayWrapper>

}
