 /*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package onlyoffice.docspace.api.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object that is generated by the integrator to uniquely identify a file in its system.
 *
 * @param fileKey The unique document identifier used by the service to get a link to the file.
 * @param instanceId The unique system identifier.
 * @param roomId Room ID
 * @param canEditRoom Specifies if the room can be edited out or not.
 */


data class FileReferenceData (

    /* The unique document identifier used by the service to get a link to the file. */
    @Json(name = "fileKey")
    val fileKey: kotlin.String? = null,

    /* The unique system identifier. */
    @Json(name = "instanceId")
    val instanceId: kotlin.String? = null,

    /* Room ID */
    @Json(name = "roomId")
    val roomId: kotlin.String? = null,

    /* Specifies if the room can be edited out or not. */
    @Json(name = "canEditRoom")
    val canEditRoom: kotlin.Boolean? = null

) {


}

